port:  5000
markdown: kramdown
name: "EITC Works!"
url: http://eitcworks.org
encoding: utf-8
timezone: America/Chicago
description: "Pinpoint how doubling the state Earned Income Tax Credit (EITC) would help lift families out of poverty and boost local economies across Illinois."
gems:
  - jekyll-redirect-from